apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bvjtsnnhf-go 
  janus-idp.io/tekton: bvjtsnnhf-go
  backstage.io/kubernetes-id: bvjtsnnhf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bvjtsnnhf-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  